- name: Terraform Plan
  env:
    TF_VAR_yc_token: ${{ secrets.YC_TOKEN }}
    TF_VAR_cloud_id: "b1g811k1u7vur9c50o56"
    TF_VAR_folder_id: "b1guevbvpqmirfgfolig"
    TF_VAR_default_zone: "ru-central1-a"
    TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
  run: terraform plan
